---
- name: "install"
  apt:
    update_cache: true
    name:
      - php{{ php_version }}-fpm
      - php{{ php_version }}-curl
      - php{{ php_version }}-iconv
      - php{{ php_version }}-json
      - php{{ php_version }}-intl
      - php{{ php_version }}-pgsql
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - php{{ php_version }}-opcache
    state: present

- name: "composer"
  script:
    cmd: ../scripts/composer.sh
    creates: /usr/local/bin/composer

- name: "configuration"
  template:
    src: ../templates/php.ini
    dest: /etc/php/{{ php_version }}/fpm/php.ini
  notify:
    - php restart
